TOP_SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT",
    "AVAXUSDT", "MATICUSDT", "DOTUSDT", "SHIBUSDT", "TRXUSDT", "LINKUSDT", "OPUSDT",
    "ARBUSDT", "NEARUSDT", "ETCUSDT", "FILUSDT", "ICPUSDT", "LTCUSDT", "XLMUSDT",
    "TONUSDT", "HBARUSDT", "APTUSDT", "GRTUSDT", "SANDUSDT", "MKRUSDT", "AAVEUSDT",
    "RUNEUSDT", "EGLDUSDT", "FTMUSDT", "THETAUSDT", "XECUSDT", "INJUSDT", "KAVAUSDT",
    "ZILUSDT", "DYDXUSDT", "CRVUSDT", "KSMUSDT", "TWTUSDT", "LDOUSDT", "WOOUSDT",
    "ENSUSDT", "GMTUSDT", "CELOUSDT", "CFXUSDT", "BLZUSDT", "ASTRUSDT", "LRCUSDT",
    "ANKRUSDT", "RSRUSDT", "YFIUSDT", "FLOWUSDT", "STORJUSDT", "CKBUSDT", "BATUSDT",
    "OCEANUSDT", "ZRXUSDT", "RENUSDT", "CHZUSDT", "1INCHUSDT", "ALPHAUSDT", "NMRUSDT",
    "BALUSDT", "COMPUSDT", "DODOUSDT", "SXPUSDT", "CVCUSDT", "API3USDT", "BANDUSDT",
    "LINAUSDT", "ICXUSDT", "FETUSDT", "OMGUSDT", "ARDRUSDT", "QNTUSDT", "SKLUSDT",
    "VETUSDT", "BICOUSDT", "AGIXUSDT", "HIGHUSDT", "STMXUSDT", "FLMUSDT", "BELUSDT",
    "ALICEUSDT", "TVKUSDT", "JOEUSDT", "UFTUSDT", "XNOUSDT", "SUPERUSDT", "TLMUSDT",
    "RAYUSDT", "BAKEUSDT", "CTSIUSDT", "PERPUSDT", "DEXEUSDT", "NUUSDT", "REEFUSDT",
    "TRBUSDT", "LITUSDT"
]
    


REFRESH_INTERVAL = 15000  # 15 seconds


# GUI refresh interval (ms)
REFRESH_INTERVAL = 15000
 